# Variant B: existingSecret points at a secret name that isn't actually
# present yet (e.g. Vault Agent Injector hasn't created/synced it, or a
# name/key mismatch). The volume mount is `optional: true`, so the pod
# stays healthy -- but the license file is simply absent.
license:
  existingSecret: n4k-license-not-yet-injected
